#!/bin/sh
# oPKGui has no background daemon (STARTABLE=no in INFO); this is a stub
# so Package Center's framework has something to call if it ever does.
case "$1" in
    start|stop|status)
        exit 0
        ;;
    *)
        exit 1
        ;;
esac
